# 'bundle exec jekyll serve' to bundle and serve site locally

# Build settings
markdown: GFM
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: 'default'

# Site settings
title: Operation Turn Boone Blue
subtitle: 'Organizing to Elect Progressives in Belvidere and Boone County'
email: mdhart1@gmail.com
url: 'https://michaeldhart.github.io'
baseurl: '/otbb-web'
twitter:
  username: TurnBooneBlue
encoding: 'utf-8'

# Content settings
include:
  - pages
  - posts

defaults:
  # pages
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      classes: wide
      title: 'You should set the title front matter to override for this page'
      header:
        overlay_image: /assets/images/courthouse.jpg
        overlay_filter: rgba(25, 59, 121, 0.8)
      author_profile: false

  # posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
