# 'bundle exec jekyll serve' to bundle and serve site locally

# Build settings
markdown: GFM
source: src
destination: dest
include:
  - _pages
  - _blog
  - _collections
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: 'default'

# Site settings
title: Operation Turn Boone Blue
subtitle: 'Organizing to Elect Progressives in Belvidere and Boone County'
url: 'https://michaeldhart.github.io'
baseurl: '/otbb-web/dest/'
encoding: 'utf-8'
atom_feed:
  hide: true
footer:
  links:
    - label: 'Facebook'
      icon: 'fab fa-fw fa-facebook-square'
      url: ''
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/TurnBooneBlue'
    - label: 'Instagram'
      icon: 'fab fa-fw fa-instagram-square'
      url: 'https://www.instagram.com/turnbooneblue'

# Content settings
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /pages/:basename.html
      layout: 'single'
      title: 'You should set the title front matter to override for this page'
      header:
        overlay_image: assets/images/big_thunder_park.jpg
        overlay_filter: rgba(25, 59, 121, 0.8)
      author_profile: false
  - scope:
      path: '_blog'
    values:
      permalink: /blog/:year/:month/:day/:title.html
      layout: 'single'
      title: 'You should set the title front matter to override for this page'
      excerpt: ''
      header:
        overlay_image: assets/images/big_thunder_park.jpg
        overlay_filter: rgba(25, 59, 121, 0.8)
      author_profile: true
      read_time: false
      share: false
      related: true
      classes: wide
  - scope:
      path: '_collections'
    values:
      layout: 'collection'
      title: 'You should set the title front matter to override for this page'
      header:
        overlay_image: assets/images/big_thunder_park.jpg
        overlay_filter: rgba(25, 59, 121, 0.8)
      author_profile: false
collections:
  blog:
    output: true
